apiVersion: skaffold/v3
kind: Config
metadata:
  name: sia-copilot
build:
  artifacts:
    - image: northamerica-northeast1-docker.pkg.dev/cio-gke-devops-e4993356/applications/sia-copilot/sia-copilot-base
      docker:
        buildArgs:
          ENV_FILE: '{{.ENV_FILE}}'
          NPMRC: '{{.NPMRC}}'
        cacheFrom:
          - northamerica-northeast1-docker.pkg.dev/cio-gke-devops-e4993356/applications/sia-copilot/sia-copilot-base
    - image: northamerica-northeast1-docker.pkg.dev/cio-gke-devops-e4993356/applications/sia-copilot/sia-copilot-st
      docker:
        buildArgs:
          ENV_FILE: '{{.ENV_FILE}}'
          NPMRC: '{{.NPMRC}}'
        cacheFrom:
          - northamerica-northeast1-docker.pkg.dev/cio-gke-devops-e4993356/applications/sia-copilot/sia-copilot-st
      requires:
        - image: northamerica-northeast1-docker.pkg.dev/cio-gke-devops-e4993356/applications/sia-copilot/sia-copilot-base
          alias: APP_BASE
  tagPolicy:
    gitCommit:
      ignoreChanges: true
  local:
    useDockerCLI: true
    useBuildkit: true
manifests:
  helm:
    releases:
      - name: sia-copilot
        remoteChart: oci://northamerica-northeast1-docker.pkg.dev/cio-gke-devops-e4993356/charts/cio-gke-deployment
        valuesFiles:
          - helm/values-st.yaml
        namespace: sia-copilot
        version: 1.31.0
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_sia_copilot_sia_copilot_st}}'
          image.tag:
            "{{.IMAGE_TAG_sia_copilot_sia_copilot_st}}@{{.IMAGE_DIGEST_sia_copil\
            ot_sia_copilot_st}}"
deploy:
  helm: {}
profiles:
  - name: st
  - name: pr
    patches:
      - op: replace
        path: /build/artifacts/1/image
        value: northamerica-northeast1-docker.pkg.dev/cio-gke-devops-e4993356/applications/sia-copilot/sia-copilot-pr
      - op: replace
        path: /build/artifacts/1/docker/cacheFrom
        value:
          - northamerica-northeast1-docker.pkg.dev/cio-gke-devops-e4993356/applications/sia-copilot/sia-copilot-pr
      - op: replace
        path: /manifests/helm/releases/0/setValueTemplates/image.tag
        value:
          "{{.IMAGE_TAG_sia_copilot_sia_copilot_pr}}@{{.IMAGE_DIGEST_sia_copilot_s\
          ia_copilot_pr}}"
      - op: replace
        path: /manifests/helm/releases/0/valuesFiles
        value:
          - helm/values-pr.yaml
      - op: replace
        path: /manifests/helm/releases/0/setValueTemplates/image.repository
        value: '{{.IMAGE_REPO_sia_copilot_sia_copilot_pr}}'
