name = "kevin-cfw-nextjs-starter-ui"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[env.development]
name = "kevin-cfw-nextjs-starter-ui-dev"
vars = { ENVIRONMENT = "development" }

[env.staging]
name = "kevin-cfw-nextjs-starter-ui-staging"
vars = { ENVIRONMENT = "staging" }

[env.prototype]
name = "kevin-cfw-nextjs-starter-ui-prototype"
vars = { ENVIRONMENT = "prototype" }

# D1 Database configuration (uncomment and create database if needed)
# [[d1_databases]]
# binding = "DB"
# database_name = "starter_kit_db"
# database_id = "placeholder-id" # Will be replaced with actual ID after creation

# Example KV namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "placeholder-id" # Will be replaced with actual ID after creation

# Example R2 bucket for file storage (uncomment and create bucket if needed)
# [[r2_buckets]]
# binding = "FILES"
# bucket_name = "starter-kit-files"