riskThreshold: 30
groupConfigProfile: CIO
automatedReleaseApproved: false
useGithubEvents: true
ignoredFiles:
  - package-lock.json
  - yarn.lock
riskInputs:
  - name: gitBranchProtection
  - name: innersource
  - name: linesChanged
  - name: semanticCommit
  - name: changedFiles
    matchChangesGlobPatterns:
      "**/*.*": low
      "**/*.js": medium
      src/pages/_@(middleware|app|document).js: high
      src/components/@(App|Document)/**: high
      next.config.mjs: high
      .github/**: critical
      openshift/**: critical
      Dockerfile: critical
      tsconfig.json: critical
    requireChangesGlobPatterns:
      "**/*.@(test|spec).*": medium
  - name: prDescription
  - name: testCoverage
    covReportPath: coverage/coverage-summary.json
  - name: webStarterKitHealth
  - name: gkeTemplateHealth
    alwaysEvaluate: false
